### ISSUE TITLE
Add loadable agents to the backend

### ISSUE THREAD

**Issue by clalancette** [maliput/delphyne#173]
We would like to have the ability to load in agents (more-or-less vehicles) dynamically at runtime into the simulation.  The goal is to be able to have agents developed completely outside of delphyne, and then loaded into a scenario.  The basic tasks here are:

**Work Items**

* [x] Get the low-level plumbing working for agents, probably using the ignition-common plugin subsystem #213 
* [x] Define an abstract base class that all agent plugins will have to implement #213 
  * [x] Base class needs to be a "System", in the drake sense of the word
  * [x] Need to have inputs and outputs
  * [x] Need to be able to parameterize the agent at startup time (pass in a map of parameters, maybe?)
* [x] Conversion of existing Cars
  * [x] Simple car: #237 
  * [x] Trajectory car #265 
  * [x] MOBIL car #301 
  * [x] Maliput car https://github.com/ToyotaResearchInstitute/delphyne/tree/add-loadable-maliput-railcar
* [x] Integration with python https://github.com/ToyotaResearchInstitute/delphyne/tree/loadable-python
* [x] Fix bug where return value from `configure` is not being checked
* [-] Formalize error handling from `configure` and from `AddLoadableModule` (skip till we have a need)
* [x] Add default directory for plugin lookup: `~/.delphyne/plugins`, with override from environment variable
* [-] Add further plugin override via YAML config file (currently uses an environment variable)
* [-] Add tests for the plugins (ala [#300](https://github.com/ToyotaResearchInstitute/delphyne/issues/300)) - Probably don't need this if we switch to a has-a implementation, as the agent code and tests for them will be inside drake.

**Documentation**

* [x] For users and developers in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.jmn7mlfgk2s8)
* [x] Document `configure` virtual method to describe design and usage considerations #213 

**Polish** (see #346)

* [x] Try out SHARED linking to drake and co. make sure it works for us
* [x] Document in the delphyne guide somewhere our design choices ... and not STATIC and why!
* [x] Open the question in ignition_common re RTLD_LAZY or RTLD_NOW.
* [x] Refactor car references in `automotive_simulator.cc` to agents.
* [x] Keep agent libraries separate (easy to know what's available on the filesystem) but collapse CMake code
* [ ] Bugfix segfault of the python script, #376 
* [x] (Daniel) Switch to a has-a rather than a is-a relationship and pull the drake car code itself
* [x] (stretch)(Daniel) Deal with the `setPlugin` constraint
* [ ] (Daniel) Understand why the maliput car has delayed configuration (and causing us a second step in configuration) - This is because we can't set parameters until we have a context, and we don't have a context until we create a simulation object.  The simulation object must be created *after* the system diagram is hooked together (i.e. `Configure` time), so I think we have to have a two-step setup here.

**Integration**

* [x] Remove non-loadable code from `automotive_simulator.cc` (this may be somewhat difficult because most of the tests need to use `AddPriusSimpleCar`, so we'd have to figure out how to deal with that)

**Demo Goal**

* [x] A new demo (not demo_launcher.py) enabled with the python layer that only loads and covers the loadable agents we have right now

**Out of Scope**

Dynamic reconfigure for scriptlet control will be left to a later milestone. Since it's a plugin framework with a fixed api, you can't just singly expose an api from this car, and yet another from another car. Likely some api with a generic key/value signature should help alleviate this situation.
  
Due to a limitation in ignition-common currently, implementations of the loadable vehicles have to derive from classes like: `AgentPluginDoubleBase`.  In the future, it will be possible to templatize these, so the implementations can derive from `AgentPluginBase<T>`.
