### ISSUE TITLE
Delphyne in CI (Logging & Replay)

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#184]
* [Milestone 3 Planning](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.7o75ni93uzsf)

**Goals**

Primary purpose is to debug problematic CI runs post-humourously without having to resurrect the code workspace. What does this need?

* What would be needed to enable visualising
  * This will be scenario dependent (e.g. presence of a TRI traffic car)
  * Assume that we want to log everything that has a topic, all the time
* Out of scope:
  * how and where to put/send logs at the end of the run
  * setting the speed of the replay (just replay at realtime rate)
  * (for now) streamlining the list of things to log
  * (for now) any extra information about the simulation run (e.g. result & statistics)

**High Level Work Items**

**Backend**

* [x] default logs to `$HOME/.delphyne/logs`. Issue #489 
* [x] environment variable or simulator option to redirect logging if desired. Issue #490
* [x] default naming format to YYMMDD-HHMM.db (or similar). Issue #489.
* [x] c++ api and bindings for overriding the location/name of the log file. Issue #490
* [x] c++ api and bindings for enabling/disabling the logging subsystem. Issue #489.
* [x] log what would be necessary to replay and of interest to the visualiser. Issue #492.
* [x] check that logging occurs, even if the visualiser is not present. Issue #491.
* [x] audit the services and how they are handled. Issue #491.
* [x] propose how to handle models / meshes (assume they are existing / pack into the .db). Issue #492.

**Replayer**

* [x] process that publishes the log for the visualiser. Issue #493.
* [x] services for pausing, stepping, resuming, rewinding (requests from the visualiser). Issue #493
* [x] process that launches the replayer and visualiser simultaneously. Issue #494.

**Visualiser**

* [x] A widget with slider that permits sliding through the log (time travel - pause, step, rewind, resume). Issue #495.

**Documentation**

* [x] user notes on how to replay in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.ok231nuz87j4). Issue #496.
* [x] developer notes in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.bhx1904e4y00) (current architecture, design choices etc). Issue #496.

**Success Criteria**

* [x] A non-dev can run our demos, find logs, run the replayer/visualiser without documentation (fallback, with documentation)
* [x] A replay can be successfully time travelled (pause, step, resume, rewind) from the visualiser

**Demo Goal**

* [x] Run a simulation, then replay it in the visualiser from the log
* [x] Demonstrate pausing, stepping and resuming a replay from log in the visualiser
