### ISSUE TITLE
Manipulating the Timestream

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#185]
Two parts to this project - basic pause/step/resume functionality and a time travel capability. The latter needs to go through a design step, starting that [here](https://docs.google.com/document/d/11tMiOYLP5RzaokY0-afNDJRlNkUxShVCoG-5Rr_3Oxg).

**Backend**

* [x] pause/step/resume functionality, with ign services to manipulate these
* [x] option to be able to start paused (w/ #180)

**Frontend**

* [x] connect to the pause/step/resume functionality in the backend
* [x] decision about whether to include time travel in Milestone #2 or punt to #3.

**Documentation**

* [x] For developers in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.l86yu61fvg13) (anything curious + command line tool instructions)

**Demo Goal**

Seme of these will have dependencies from other milestone subprojects.

* [x] demonstrate pausing, stepping and resuming a simulation from the visualiser
* [x] demonstrate pausing, stepping and resuming from the command line
* [x] demonstrate starting a simulation paused (w/ #180)

----

**Fixes and Polish**

* [x] multi-step should run at the same speed as the simulation (#326)
* [x] put the time control widget over on the right hand side of the screen in our default layout
* [ ] button styling to match the system's option (https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/75)
* [ ] Gui key-bindings (P, S, R) (https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/76)

----

**Priorities**

Punting time travel to either a separate meta issue or milestone #3.

**Risks**

* Time Travel related work is more complicated and might take longer than expected (we did one for behaviour tree monitoring/playback some time ago).
