### ISSUE TITLE
Display Widget & Common Plugins

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#186]
* [Milestone 3 Planning](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.7o75ni93uzsf)
* [Design Doc](https://docs.google.com/document/d/1szeE4G9UTK_bk0SI8FOtGpoEYt4CS5wnDmeeIbx9rj8)

**Goals**

Enable an RViz style approach to enabling painting on the main window via a small widget that lets users customise / configure how it gets rendered.

**High Level Work Items**

* [x] Display Widget
* [x] Grid Display Plugin (~Rviz)
* [x] Realtime Rate Plugin
* [x] Save/load configurations
* [ ] ~Python convenience api for starting our demos from a specific configuration~ (Can be specified in the .config layout file as in RViz, for which python convenience api already exists)
* [x] Documentation for users & developers in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.r2kit599ol6a) 

**Success Criteria**

* [x] All of our demos making use of both grid and realtime rate plugins
