### ISSUE TITLE
Scene Tree Widget

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#187]
**Current Status**

This widget will visualize all fields contained in a `scene` [message](https://bitbucket.org/ignitionrobotics/ign-msgs/src/43530325244f3254c79867112767b25bef81b058/proto/ignition/msgs/scene.proto?at=default&fileviewer=file-view-default). 

**Work Items**

* [x] Review the proposed list of values
* [ ] Fix the hanging launch, #324 

**Documentation**

* [x]  For developers in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.l86yu61fvg13), specifically the list of items the scene tree widget currently shows with instructions for the demonstration.

**Demo Goal**

* [x] Demonstrate on Delphyne exhibiting the specified list.
