### ISSUE TITLE
Bridge Deprecation

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#188]
Currently moving this across one at a time. Note that we are dropping backwards compatibility to drake visualiser along the way.

**Work Items**

* [x] Drop `DRIVING_COMMAND_(*)`
* [x] Drop `DRAKE_VIEWER_STATUS`
* [x] Drop `(.*)_SIMPLE_CAR_STATE`
* [x] Drop `DIRECTOR_TREE_VIEWER_RESPONSE`
* [x] Cleanup and code organization 
    * [x] #232
    * [x] #233
    * [x] #234 
    * [x] #235 
    * [x] #236
    * [x] #218 
    * [x] #361
* [x] Merge AutomotiveSimulatorPort branch back to master (#239)
* [x] Enable the python tests/`tools/run_tests.sh` script in CI

**Demo Goal**

* [x] launch without a bridge.
