### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#191]
**Current Status**

* Can drag and drop any property from a topic in the plotting widget, plot against a time axis
* Can combine variables in the same plot / multiple plots
* Export the plot to pdf/csv, not png?
* Hover with a mouse, you can see the current value
* Edit the name of the plot

**Work Items**

* [x] Review once all PR's and documentation is in
* [ ] Second iteration (if needed)

**Documentation**

* [x] For developers in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.q4nu39pcm38q) (including instructions for a demonstration)
 
**Demo Goal**

* [x] Walkthrough with instructions
