### ISSUE TITLE
CMake Cleanup & Other Things

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#296]
In the interests of keeping it simple/fast development

* [x] `cmake/Ronn2Man.cmake` and  `cmake/upload_doc.sh.in` (#354, [delphyne-gui#88](https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/88))
* [x] avoid mixing STATIC/SHARED everywhere (#341, #342, #437)
* [ ] make better use of `target_include_directories` than liberal splatterings of `include_directories`
* [x] drop windows/macos concerns (#369)
* [x] drop visibility (including `DELPHYNE_BACKEND_VISIBLE`)  (#342, #353, [delphyne-gui#84](https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/84), [delphyne-gui#87](https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/87))
* [x] drop or fix versioning &#8680; #471
* [x] backend/tests to tests directory &#8680; #347
* [x] switch to a regular src/include/tests layout, ala #304 &#8680; (#385, #407, #432)
* [ ] rationalise library/file organisation
* [x] drop pkg-config support (one less thing to maintain)(#356)
* [x] put `delphyne-config/targets/version.cmake` are in good order (#350)(#356, [delphyne-gui#92](https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/92))
* [ ] general cleanup of the root cmake / cmake modules
* [x] just delphyne namespace, no need (yet) to nest it further
* [x] export `delphyne::protobuf_messages` and eliminate copies in delphyne-gui  (#350, [delphyne-gui#83](https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/83))
* [x] `delphyne-gui` should use `delphyne`'s `system.h` &#8680;  #442
* [x] fix include order, as per [google style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) (#441)
* [ ] `delphyne` and `delphyne-gui` should use same header extensions (.h or move away from drake to .hh or .hpp)
* [x] `delphyne` and `delphyne-gui` should use same file naming convention (lowercase or camelcase) (#439 and delphyne-gui's [#122](https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/122))
* [x] ~~drop pragma once for standards accepted methods?~~ No, not important enough to shift away from drake/driving practices
