### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by basicNew** [maliput/delphyne#372]
* [Milestone 3 Planning](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.7o75ni93uzsf)
* [Design Doc](https://docs.google.com/document/d/1AI4LQ6BWbYHHsTRAG4W_sLRGaiqqMIkfA_z6XJjkq6Q)

**Goals**

Delphyne can identify and notify when collisions occur, but is not responsible for the physics of collision behaviours. i.e. just report out when a collision occurs.

**Work Items**
* [x] Research on existing ways of doing collision detection and prepare a first demo (PR #449).
* [x] Add on collision callbacks and expose in python.
* [x] A toggle for enabling/disabling the collision subsystem.
* [x] A demo, `delphyne-crash` with two agents setup for a crash.
* [x] Identify / answer open questions, sketch out the plan in the [design doc](https://docs.google.com/document/d/1AI4LQ6BWbYHHsTRAG4W_sLRGaiqqMIkfA_z6XJjkq6Q)
* [x] User & Developer Documentation in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.jmn7mlfgk2s8) -> [Collision detection](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.35b7tvu66ui4) 

**Success Criteria**

* [x] `delphyne-crash` detects the collision and responds 'appropriately' (to be determined)

**Descoped from Milestone 3**
* [ ] Define a design that scales across cars and that can be simply evolved from bounding boxes to more complex shapes. Most likely something similar to CarViz, but for geometries (see [design doc](https://docs.google.com/document/d/1I7QFrnZzxbrkbmyKkAV1KsQ8z0DuoyibN2B_S_yRyf0/edit#heading=h.sjx34iuuglmq) on arch). Opened #567 to be tackled outside M3.
* [ ] Add more info about the collision (points, depth, etc) and expose in python (#479, #460). Opened #568 to be tackled outside M3.
