### ISSUE TITLE
M2 - Final Integration / Polish

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#378]
The must-haves for a nice demo:

* [x] **Backend**: A pythonic `demo_launcher.py` (i.e. replace `automotive_demo`)
* [x] **UI**: Root cause / fix strange artifacts on the dragway #150
* [x] **UI**: Nice gradient backend like drake-visualizer had #99
* [x] **UI**: Qt styles on buttons, [delphyne-gui#75](https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/75)
* [x] **UI**: Quit always triggers saving dialog, [delphyne-gui#97](https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/97)
* [x] **UI**: Plotting plugin is crashing the visualiser, [delphyne-gui#105](https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/105) &#8680;  [delphyne-gui/pull/108](https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/108)
* [x] **Scene Tree**: has empty fields, [delphyne-gui#106](https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/106)  &#8680; [delphyne-gui/pull/109](https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/109)
* [x] **Roads**: Bugfix segfault of the python scripts when finishing, #376
* [x] **Agents**: Fix memory management issues (i.e. don't transfer roads) &#8680; #383 
* [x] **Agents**: New Trajectory Agent (doesn't have to be in the M2 demo) &#8680; #417 
* [x] **Agents**: Shift to python bound agents &#8680; #417, #425
* [x] **Agents**: Update the documentation
* [x] **Python**: User and Developer notes in the Delphyne Guide. Document the caveats in the developer's section (i.e. new type, expose it in python_bindings.cc)
* [x] **Demo**: A multilane world with lane changing cars and finite amount of time &#8680; #418

Optional Housekeeping that can be done in parallel (priority order):

* [x] **Infra**: Read non-ignition topics and services, #359  (almost non-optional!?)
* [x] **Infra**: Pull in a drake binary for CI, #352, #422
* [x] **Infra**: Some ignition improvements, #344 &#8680; ([delphyne/pull/411](https://github.com/ToyotaResearchInstitute/delphyne/pull/411), [delphyne-gui/pull/103](https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/103))
* [x] ~~**Infra**: Python package, #290 #344 &#8680; [delphyne/pull/412](https://github.com/ToyotaResearchInstitute/delphyne/pull/412)~~
* [x] ~~**Infra**: Improve the way we're finding agents in tests, #368~~ 
* [x] **Infra**: Simulation Runner should not be compiled as STATIC [#341]
* [ ] **Infra**: Tick off a few more things on the general CMake Cleanup, #296 
* [x] **UI/Time**: Realtime rate in the rendering window, #403 
* [ ] **UI/Time**: Gui key-bindings (P, S, R), https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/76
* [ ] **UI/Time**: Additional information in the time window, https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/77
* [x] **UI**: can't resize the right hand dock, https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/107
* [ ] **UI**: sometimes not resizing the rendering on loading, https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/110
