### ISSUE TITLE
Daniel's agent evolution M2 Scratchpad

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#398]
Working notes.

**Has-A Agents**

* [x] rail-car &#8680; #404
* [x] simple-car &#8680; #404
* [x] mobil-car &#8680; #404
* [x] reenable tests &#8680; #404
* [x] Port to the new and shiny trajectory agent &#8680; #417

**Non-Dynamically Loaded Agents**
* [x] SimpleCar &#8680; #417 
* [x] RailCar &#8680; #425
* [x] MobilCar &#8680; #425
* [x] Trajectory Agent &#8680; #417
* [x] Unwind dynamically loadable / plugin methods &#8680; #425
* [ ] Upstream or unwind changes to `src/systems/maliput_railcar_system.h/cc`

**ToDo**

* [x] Still need `AutomotiveSimulator::InitializeSimpleCar`? &#8680; #397 
* [x] Drop `DrakeLcmInterface` as an arg to `LoadableAgent::Configure` &#8680; #404 
* [x] Why is `initial_lane_direction` for RailCar not a parameter? It's not a context variable
* [x] Drop the template param from `AgentBase`? (it's no longer a system), no - hypothetically useful for the templated AutomotiveSimulator class in some future
* [x] `AutomotiveSimulator::get_lcm()`, `lcm_` can disappear? Yes &#8680; #408
* [x] Store `loadable_agent_initial_states_` in the agents instead of the simulator &#8680; #417, #425
* [x] Move all diagram / configuration work to the loadable agents (currently split)?
* [x] Override `DefaultContext` methods instead of an `Initialize` method?
* [x] Drop `get_system` usage in AutomotiveSimulator::InitializeAgents`, we have n-system agents
* [ ] Refactor unused? `AutomotiveSimulator::ConnectCarOutputsAndPriusVis`
* [x] Drop `get_system` usage from `AgentBase`
* [ ] SimpleCar -> TeleopCar?
* [ ] Teleop id -> name?
* [ ] (drake) refactor out lanedirection, it's discombabulating
* [ ] a unique id in AgentBase actually necessary?
* [x] move FindLane -> `maliput::FindLane` convenience library
* [ ] asserts in AddAgent should probably be just checks, err msg and return -1
* [ ] exceptions by CheckNameUniqueness in AddAgent shouldn't be exceptions

**Stretch**
* [ ] Agents that can load anytime -> get inserted between updates
* [ ] Use SceneGraph instead of the aggregator
* [ ] Parameters streaming/publishing

**TrajectoryAgent**

* [x] Dump AgentType/AgentData from TrajectoryAgent (should be handled separately?)
* [x] Rename to TrajectoryFollower (system, not an agent)
* [x] Unwind if(plugin_library_name != "trajectory-agent")  when `loadable_initial_states_` goes away

**Python**
* [ ] replace `robot_id` with human readable names

**Architecture Thoughts**

* Systems, Diagrams and *then* agents

**NotDo**

* [x] Agentcounter automagically from `AgentPluginBase`? No, necessary for uniquely id'ing a port to the aggregator. There may be other systems to be id'd, not just agents. Threading issues can also be a problem, better to have a single instance generating them.
