### ISSUE TITLE
Daniel's Agent Evolution ScratchPad

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#438]
**Upstream**
* [x] Bugfix SetDefaultState in drake &#8680; [drake/pulls/89340](https://github.com/RobotLocomotion/drake/pull/8934)

**ToDo**

* [x] completely pull in rail car
* [ ] (drake) refactor out lanedirection, it's discombabulating
* [x] completely pull in mobil car
* [ ] rename simple car to teleop car
* [ ] rename `SimpleCarState` to ???
* [ ] get init poses from initial values on pose outputs instead of calculating them
* [x] Declare AbstractState in rail_car &#8680; #467 
* [x] Refactor unused? `AutomotiveSimulator::ConnectCarOutputsAndPriusVis`
* [x] Teleop id -> name? &#8680; #481
* [x] ~~a unique id in AgentBase actually necessary? Yes, for fast identification (not strings) in simulation callbacks~~

**Stretch**
* [x] ~~Agents that can load anytime -> get inserted between updates? Can't fu with diagrams after construction, need system framework updates~~
* [ ] Parameters streaming/publishing

**Python**
* [ ] replace `robot_id` with human readable names

**Architecture Thoughts**

Jotting things down in the [Agent Architecture Design Document](https://docs.google.com/document/d/1I7QFrnZzxbrkbmyKkAV1KsQ8z0DuoyibN2B_S_yRyf0/edit#heading=h.sjx34iuuglmq)
