### ISSUE TITLE
Architectural Improvements & Bugfixes

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#453]
**Resources**

* [Milestone 3](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.fw0eby56l74g)

**Goals**

Keep tabs on the architecture and the complexity. This list will likely evolve as flags get raised while we work on items.

**Front Load**

* [x] A benchmark scenario running 20+ of our most expensive agents (currently MOBIL cars) &#8680; #455 
* [x] Splitter that sits after the vectorised `SimpleCarState_V` publisher &#8680; #504 (PR #511)
* [x] Rename and improve the `SimpleCarState` message &#8680; #505 (PR #517)
* [x] Move simulator-specific wiring out of the individual agents &#8680; (PR #481)
* [x] Diagnostics report on where unnecessary CPU costs are coming from &#8680; #455
* [x] Simple checklist list of items that caused problems (check off what has been resolved) &#8680; #455
* [x] Decide if we implement any of these remaining jobs in M3
* [x] CMake Cleanup &#8680; #472
* [x] Migrate drake automotive systems (brute force move) &#8680; #498

**Stretch Bugs**

* [x] MOBIL car in gazoo - totally loses it in the corner &#8680; #573
* [x] Car Pileup in gazoo &#8680; #545

**Success Criteria**

* [x] Issues for any remaining (hopefully non-architectural) performance problems that are killing us, but not to be resolved in M3.
* [x] Agents do not depend on (even indirectly) the simulator
* [x] Can run 20+ agents (any of the current) @ 100Hz realtime.
