### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#454]
* [Milestone 3 Planning](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.7o75ni93uzsf)
* [Design Doc](https://docs.google.com/document/d/1AI4LQ6BWbYHHsTRAG4W_sLRGaiqqMIkfA_z6XJjkq6Q)

**Goals**

Delphyne can identify and notify when collisions occur, but is not responsible for the physics of collision behaviours. i.e. just report out when a collision occurs.

**Work Items**

* [ ] A demo, `delphyne-crash` with two agents setup for a crash
* [ ] Identify / answer open questions, sketch out the plan
* [ ] <TODO: work items>
* [ ] A toggle for enabling/disabling the collision subsystem
* [ ] User & Developer Documentation in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.jmn7mlfgk2s8)

**Success Criteria**

* [ ] `delphyne-crash` detects the collision and responds 'appropriately' (to be determiend)
