### ISSUE TITLE
Diagnose CPU costs

### ISSUE THREAD

**Issue by basicNew** [maliput/delphyne#455]
Tests done on a 5-lane dragway with cars distributed in consecutive roads.

TODO: Repeat with a multilane road.

<table>
  <tr>
    <th>Frequency</th>
    <th colspan="2">With Visualizer</th>
    <th colspan="2">Without Visualizer</th>
    <th colspan="2">Without Visualizer and no publishing [2]</th>
  </tr>
  <tr>
    <th>  </th>
    <th>Max rail cars</th>
    <th>Max mobil cars </th>
    <th>Max rail cars</th>
    <th>Max mobil cars </th>
    <th>Max rail cars</th>
    <th>Max mobil cars </th>
  </tr>
  <tr>
    <th>500 Hz</th>
    <td>35 [1]</td>
    <td>8</td>
    <td>48</td>  
    <td>9</td>
    <td>160</td> 
    <td>9</td>
  </tr>
  <tr>
    <th>250 Hz</th>
    <td>70 [1]</td>
    <td>13</td>
    <td>81</td>  
    <td>13</td>
    <td>320</td> 
    <td>13</td>
  </tr>
  <tr>
    <th>100 Hz</th>
    <td>132 [1]</td>
    <td>22</td>
    <td>150</td> 
    <td>23</td>
    <td>655</td> 
    <td>25</td>
  </tr>
</table>

[1] UI lags / becomes unresponsive
[2] Topic throttling makes no difference

From this initial pass there are a couple of things we can conclude:

- Railcars are rather lightweight on CPU and the cost of visualizing them does make a difference.
- MOBIL cars are CPU hungry, so the cost of updating the UI is not relevant.
- There seems to be a slightly difference between having the visualizer running or not. This may be because of ign transport overhead or the difference between sync and async simulation runner.
- We are updating the UI at simulation frequency, so it makes sense that it lags behind with 70 cars at 250Hz.

Some next steps:
- [x] Throttle scene publishing @ 60Hz and see if there is any difference on the UI lag. Check also if there is any difference on having the scene with all the widgets vs only the scene. Final thing would be to profile the scene renderer and look for bottlenecks (https://github.com/ToyotaResearchInstitute/delphyne-gui/issues/130).
- [x] Research on the huge difference between publishing vs not publishing. @hidmic pointer out that the bottleneck may not be on the publisher itself: since the systems are lazy, if we don't publish, many other systems may not even be activated and hence lot of computations not done (e.g. aggregators, car vis applicators, etc). In any case, we should get a deep understanding of what is going on here and profile where necessary (#469)
- [x] Profile MOBIL car to discover where all the CPU is going (#470).
