### ISSUE TITLE
Delphyne Display Plugins

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#456]
* [Milestone 3 Planning](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.7o75ni93uzsf)
* [Design Doc](https://docs.google.com/document/d/1szeE4G9UTK_bk0SI8FOtGpoEYt4CS5wnDmeeIbx9rj8/edit)
* Blocked by #186 

**Goals**

Road test display plugins for users and give the visualisation enough information to start being really useful instead of promo videos.

* [ ] <TODO: design/de-risk/plan on the design doc when we're ready to start>

**Success Criteria**

Be able to view/toggle information from all of the proposed plugins in some/all of our demos.

* [ ] Maliput Plugin: enabled for all of our demos
    - Essentially port the standalone viewer to an agent display plugin
    - Success is getting to the same feature parity as the standalone one
* [x] Agent Info Plugin: enabled for all of our demos
