### ISSUE TITLE
Teleop Makeover

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#457]
**Resources**

* [Milestone 3](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.fw0eby56l74g)

**Goals**

Improve on the Teleop 1st pass.

**High Level Work Items**

* [ ] Can `SimpleCar` teleop on a 2D road surface in 3D space? Probably not
* [ ] SimpleCar -> TeleopAgent
* [ ] If no, create a `TeleopCar` that can (design question: what happens when it goes off the road?)
* [ ]  Drop-down a list of cars that can be teleop'd instead of having to explicitly type it
* [ ] Button/shortcut to bring the car to a halt
* [ ] Updated documentation in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit#heading=h.2whmjkb4cs4z)

**Success Criteria**

* [ ] The afore-mentioned functionality works in `delphyne-keyop`

**Questions**

* [ ] What do we do about 3D teleoperation, if indeed that is a problem?
* [x] What cars can/should be teleop'd? All or we just have a 'TeleopAgent'? Just TeleopAgent

**Out of Scope**

* Taking control of other agents (mid simulation) with their own autonomy
