### ISSUE TITLE
Agent Bookkeeping

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#459]
**Resources**

* [Milestone 3](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.fw0eby56l74g)

**Goals**

Keep a tab on the spaghetti in agents. This list should evolve as we work.

**High Level Work Items**

* [ ] Move simulator-specific wiring out of the individual agents &#8680; [PR 481](https://github.com/ToyotaResearchInstitute/delphyne/pull/481)
* [ ] MOBIL car is dodgy on gazoo - totally loses it in the corner
* [ ] ~~(stretch) Add/Remove agents mid-simulation: not possible, drake systems can't be removed mid-simulation~~

**Success Criteria**

Nothing specific, just resolution of the items identified.
