### ISSUE TITLE
Agents & the Ground Truth World

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#460]
**Resources**

* [Milestone 3 Planning](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.7o75ni93uzsf)

**Goals**

Manipulate agents based on context received from the ground truth world API in simulation (via scriptlets)

**High Level Work Items**

General
* [x] Safe pythonic access to the child agent (not agentbase) from scriptlets after they've been added to the simulator, #468
* [ ] Some design for the 'Ground Truth World API' and it's bindings (~maybe design doc?~ [design doc](https://docs.google.com/document/d/1Rs8h4GhbKQOjSz1T5u_0tj9rSQUQa7Zm9ImjnFB5v9U/edit#))
* [x] Equip delphyne-scriptlets with a dragway and some rail cars

Maliput
* ~~Python access to Maliput API or convenient Maliput API extensions (in delphyne/src/maliput) for programmatic or introspective purposes : not critical right now~~

Time
* [x] Python access to the simulator time

Other Vehicles
* [x] Python access to the poses of other cars (world) (just getting agents, and then poses from each is fine)
* ~~Python access to the poses of other cars on the same road (within a certain range) : a user can quickly write a python script for this~~
* [ ] Convenience api for knowing when it might 'pass' another car on a neighbouring lane
* [ ] Python access to the bounding boxes of other cars and obstacles in the world

Other
* [x] Documentation in the [Delphyne Guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit)

**Success Criteria**

Added functionality to `delphyne-scriptlets`

* [ ] a rail car that modifies its nominal speed when passing a certain point in the road (maliput)
* [x] a rail car that modifies its nominal speed after a certain time (time)
* [ ] a rail car that modifies its nominal speed when it passes the car on the 'left' (other vehicles)
