### ISSUE TITLE
Pedestrians

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#461]
**Resources**

* [Milestone 3 Planning](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.7o75ni93uzsf)

**Goals**

Enable pedestrians as TrajectoryAgents’ and fix a few loose ends with the same

**High Level Work Items**

* [ ] Visuals - probably a more general consideration of this
* [ ] Distinct type of its own (separate to vehicles) so that it can be used with ground truth api search filters
* [ ] Access to pedestrians via the ground truth world api (c++ and python)
* [ ] Vehicle agent updates to 'sense' and 'react' to pedestrians

**Success Criteria**

 * [ ] `delphyne-dragway` : a pedestrian walking across the dragway and cars slowing down for it
