### ISSUE TITLE
Obstacles

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#462]
**Resources**

* [Milestone 3 Planning](https://docs.google.com/document/d/1UWfuwDBfYKSq-Jj4dM1AK6BiaV3v3DHA3PECetmGhdw/edit#heading=h.7o75ni93uzsf)
* Blocked by #460 

**Goals**

Hay bales on the road! We use these at TRI field tests. A significant difference is that this type is static and thus should be handled somewhat differently to other agents (though an argument could be made for making it a stationary `TeleopAgent`.

**High Level Work Items**

* [ ] A static agent
* [ ] Distinct type of its own (separate to vehicles) so that it can be used with a ground truth api
* [ ] Visuals
* [ ] AddObstacle api to AutomotiveSimulator
* [ ] Python access to poses of obstacles of the world via a Ground Truth Api
* [ ] Python access to bounding boxes of obstacles of the world via a Ground Truth Api
* [ ] Bounding box collisions

**Success Criteria**

Ramp up `delphyne-scriptlets` with obstacle capabilities. 

 * [ ] place an obstacle in the middle of the dragway
* [ ] move the obstacle in the middle of the simulation (from python scriptlet)
* [ ] a rail car successfully stops in front of an obstacle placed in lane
