### ISSUE TITLE
CMake Cleanup Part 2

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#472]
* [x] make use of `target_include_directories` instead of `include_directories` &#8680; #482
* [x] collapse library targets in `backend` &#8680; #507
* [x] LCM still needed in `SearchForStuff.cmake`? No &#8680; #473
* [x] review and consider dropping `SearchForStuff.cmake` &#8680; #473
* [x] review and drop unused parts of `Utils.cmake` (drop entirely?)  &#8680; #473, #482
* [x] review the CFlags maze #565 
* [x] review and simplify, drop unused parts in the root `CMakeLists.txt` &#8680; #482
