### ISSUE TITLE
Replayer play, pause, step, rewind

### ISSUE THREAD

**Issue by nkoenig** [maliput/delphyne#493]
### Tasks

- [x] Make a `/replayer` process that publishes the logs for the visualiser through an `ignition::transport::log::Playback` class instance.
- [x] Ignition transport services based API (hit by the visualiser) for:
     - [x] Pausing and resuming log playback.
          - [x] Add Pause() and Resume() methods to the `ignition::transport::log::PlaybackHandle` class.
          - [x] Advertise `/replayer/resume` and `/replayer/pause` services from the process.
     - [x] Stepping log playback.
          - [x] Add Step() method to the `ignition::transport::log::PlaybackHandle` class.
          - [x] Advertise `/replayer/step` service from the `/replayer` process.
     - [x] ~Rewinding~ Seeking log playback.
         - [x] Add ~Rewind()~ Seek() method to the `ignition::transport::log::PlaybackHandle` class.
         - [x] Advertise ~`/replayer/rewind`~ /replayer/seek service from the `/replayer` process.

#### Extras

- [x] Ignition transport topic based feedback (to be consumed by the visualiser), namely:
     - [x] Playback status notifications.
          - [x] Add StartTime(), CurrentTime(), EndTime() and IsFinished() getters to the  `ignition::transport::log::PlaybackHandle` class.
          - [ ] ~Add WaitUntilNextMessage(int timeout) method to the  `ignition::transport::log::PlaybackHandle` class.~ NOT NECESSARY
          - [x] Publish a `/replayer/status` topic from the `/replayer` process at a fixed rate.

### Notes

Upstream `ignition-transport` branch/fork/repo to work on: `default`
