### ISSUE TITLE
Make simulation Context available to Agents

### ISSUE THREAD

**Issue by hidmic** [maliput/delphyne#549]
#### Description
We need to push `Context` into `Agent` instances, for them to be able read/write their `Diagram` counterpart's state during API calls. Additionally, measures need to be taken to prevent `Context` usage before the `Agent` is _bound_ to a simulation. 

Connected to #460 and #474. See [design document](https://docs.google.com/document/d/1I7QFrnZzxbrkbmyKkAV1KsQ8z0DuoyibN2B_S_yRyf0/edit?ts=5baac6a0#heading=h.851g1t3bbz95) for further reference.
#### Tasks
- [ ] Bind `Context` to `Agent` upon simulation setup.
- [ ] Implement basic _safe_ API that makes use of agents' context.

#### Demo
- [ ] Basic API use case with a `RailFollower`.
