### ISSUE TITLE
Milestone I

### ISSUE THREAD

**Issue by stonier** [maliput/delphyne#61]
I'd like to get what we have now in a more polished form for the Milestone 1 demo.

**Development & Infra**

* [x] Saner development workflow / updated README (#60)
* [ ] (stretch) Attach Reviewable to this repo (#84)
* [ ] (stretch) Missing transport3.yaml, cmdtransport3.rb in deb (though deb upgrade not nec. yet) (#85)
* [ ] (stretch) Use ament to build/manage the development workflow (#83)
* [ ] (stretch) CMake switch (#86)

**Frontend**

* [x] Lighting (#62)
* [x] Fix ignition-rendering bug that changes background back to black on resize ([ignition-rendering #26](https://bitbucket.org/ignitionrobotics/ign-rendering/pull-requests/26/))
* [x] Grid - probably put in a plane as a stop-gap for now (#63)
* [x] Problems with transforms
* [x] Obj support in ignition-common ([ignition-common #68](https://bitbucket.org/ignitionrobotics/ign-common/pull-requests/68))
* [x] Obj support in visualizer (#75)
* [x] Rendering widget UX tweaks (start in the central dock)
* [ ] Rendering widget craziness (disappears when losing focus, flickering)(only on Daniel's laptop?) (#87)
* [x] PR for the Mesh installs in drake/automotive_demo (c.f. drake/manipulation/models/BUILD) (PR RobotLocomotion/drake#7043)
* [x] Add topic spy plugin, remove TopicEcho and TimePanel plugins (#68)
* [x] Topic Spy - Does not show the complete list of topics yet
* [x] Use system QT style (#71)
* [ ] (Stretch) why do ignition packages all disable SSE4? (#88)
