### ISSUE TITLE
Update delphyne to drake 0.16.1

### ISSUE THREAD

**Issue by agalbachicar** [maliput/delphyne#682]
Errors and warnings when compiling with drake 0.16.1

- [X] Missing functionality (fixed in #686)

```bash
/home/agalbachicar/Localwork/tri_ws/src/maliput_ws/src/delphyne/src/backend/ign_subscriber_system.h:53:51: error: ‘std::unique_ptr<drake::systems::AbstractValues> delphyne::IgnSubscriberSystem<IGN_TYPE>::AllocateAbstractState() const [with IGN_TYPE = ignition::msgs::AutomotiveDrivingCommand]’ marked ‘override’, but does not override
   std::unique_ptr<drake::systems::AbstractValues> AllocateAbstractState() const override {
```

See https://github.com/RobotLocomotion/drake/pull/12792

- [x] Warning in `MultibodyPlant` (fixed in #684)
```
/home/agalbachicar/Localwork/tri_ws/src/maliput_ws/src/delphyne/src/backend/geometry_utilities.cc:19:44: warning: ‘drake::multibody::MultibodyPlant<T>::MultibodyPlant() [with T = double]’ is deprecated: 
DRAKE DEPRECATED: Use MultibodyPlant(double) with time_step = 0.
The deprecated code will be removed from Drake on or after 2020-05-01. [-Wdeprecated-declarations]
   drake::multibody::MultibodyPlant<double> plant;
```

- [x] Warning in integrator: (fixed in #684)

```bash
/home/agalbachicar/Localwork/tri_ws/src/maliput_ws/src/delphyne/src/backend/agent_simulation_builder.cc:315:45: warning: ‘U* drake::systems::Simulator<T>::reset_integrator(Args&& ...) [with U = drake::systems::RungeKutta2Integrator<double>; Args = {drake::systems::Diagram<double>&, const double&, drake::systems::Context<double>*}; T = double]’ is deprecated: 
DRAKE DEPRECATED: Use void or max-step-size version of reset_integrator() instead.
The deprecated code will be removed from Drake on or after 2020-05-01. [-Wdeprecated-declarations]
   drake::systems::RungeKutta2Integrator<T>* integrator =
                                             ^~~~~~~~~~
```

Connected to https://github.com/ToyotaResearchInstitute/dsim-repos-index/issues/122
