### ISSUE TITLE
Update Delphyne Guide

### ISSUE THREAD

**Issue by francocipollone** [maliput/delphyne#806]
### Context

[Delphyne guide](https://docs.google.com/document/d/1tQ9vDp084pMuHjYmtScLB3F1tdr4iP9w7_OTcoSM1zQ/edit?usp=sharing) hasn't been updated for a while and lately many changes related to the ignition migration have taken place.

I've created another document based on the first one as it can be modified. [Delphyne Guide 2021](https://docs.google.com/document/d/1Vd4KVPZ7jqVpWXXSKJhVazsSjE6DT2nU2H8GsZ66gak/edit#)

### Tasks

On code
 - [x] Fixes log argument for the demos when no output filename is passed. e.g. `delphyne_gazoo --log`: 
        https://github.com/ToyotaResearchInstitute/delphyne/pull/805 
        https://github.com/ToyotaResearchInstitute/delphyne_demos/pull/24
 - [x] During ignition migration some files got named with a "2" as suffix. This should be cleaned up: https://github.com/ToyotaResearchInstitute/delphyne_gui/pull/455
 - [x] Update Readme file https://github.com/ToyotaResearchInstitute/delphyne/pull/807
 - [x] Teleop plugin resize. https://github.com/ToyotaResearchInstitute/delphyne_gui/pull/458
 - [x] Fix `delphyne_city` demo. https://github.com/ToyotaResearchInstitute/delphyne_demos/pull/26
 - [x] Fix `delphyne_city` demo in focal. https://github.com/ToyotaResearchInstitute/delphyne/pull/813
 - [x] Fix `delphyne_crash` demo: https://github.com/ToyotaResearchInstitute/delphyne/issues/808
 - [x]  Adds smoke tests for all the demos https://github.com/ToyotaResearchInstitute/delphyne_demos/pull/28
 - [x] Fix layout selection when running demos. https://github.com/ToyotaResearchInstitute/delphyne_gui/pull/459 https://github.com/ToyotaResearchInstitute/delphyne_demos/pull/29
 - [x] Fix gui plugin list https://github.com/ToyotaResearchInstitute/delphyne_gui/issues/460
 - [x]  Fix text render in the visualizer: https://github.com/ToyotaResearchInstitute/delphyne_gui/issues/469

 On document
 - [x] Correct naming in the entire document: e.g `delphyne-replay` --> `delphyne_replay`
 - [x] Update pictures using `ign-gui3` based visualizer when necessary.
 - [x] Update `Build & Installation` section which also implies a modification at delphyne's README that is outdated.
 - [x] Update `Style Checking & Formatting` section: cpplint isn't being used.
 - [x] Verify code snippets related to `Python layer`.
 - [x] Verify info about `Agent Framework`.
 - [x] Adds an example on how to use the Agent.
 - [x] Adds info about BehaviorTree machinery
 - [ ] Update On the RoadMap section(?)
 - [x] Update collision detection snippet code as it doesn't work.
 - [x] Update info about `PlaybackWidget` as it was replaced by `PlaybackPlugin`.
 - [x] Update `Manipulating the Time Stream` section.
 - [ ] Plot widget section: It wasn't migrated to ign-gui3. https://github.com/ToyotaResearchInstitute/delphyne_gui/issues/456
 - [x] Add info about the teleop plugin
 - [x] Add info about the TopicStats plugin
 - [x] Add info about the TopicViewer plugin
 - [x] Update info about Scene Tree Widget: This plugin was reimplemented as ign-gui3 didn't migrate it from ign-gui0.
 - [x] Update `Displays Widget` section as many were reimplemented.
 - [x]  Adds info about gui configuration save/load.

Bonus
 - This guide probably should be added to `maliput_documentation`/ `delphyne_documentation`(if exists in the future)
